import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';
import '../../core/app_controller.dart';
import '../../data/models.dart';

class ExpensesScreen extends StatefulWidget { const ExpensesScreen({super.key}); @override State<ExpensesScreen> createState()=>_ExpensesScreenState(); }
class _ExpensesScreenState extends State<ExpensesScreen>{
  Future<void> _add() async { final app=context.read<AppController>(); final s=AppStrings(app.bangla); final amount=TextEditingController(); final note=TextEditingController(); String category='General'; final ok=await showModalBottomSheet<bool>(context:context,isScrollControlled:true,builder:(ctx)=>StatefulBuilder(builder:(ctx,setLocal)=>Padding(padding:EdgeInsets.fromLTRB(18,18,18,MediaQuery.of(ctx).viewInsets.bottom+18),child:Column(mainAxisSize:MainAxisSize.min,children:[Text(s.expenses,style:Theme.of(ctx).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:12),TextField(controller:amount,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:InputDecoration(labelText:s.amount,prefixText:'৳ ',border:OutlineInputBorder(borderRadius:BorderRadius.circular(18)))),const SizedBox(height:10),DropdownButtonFormField<String>(value:category,items:const ['General','Transport','Internet','Tools','Other'].map((m)=>DropdownMenuItem(value:m,child:Text(m))).toList(),onChanged:(v)=>setLocal(()=>category=v??'General'),decoration:InputDecoration(labelText:s.category,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18)))),const SizedBox(height:10),TextField(controller:note,decoration:InputDecoration(labelText:s.notes,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18)))),const SizedBox(height:14),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:Text(s.save))])))); if(ok!=true)return; final value=double.tryParse(amount.text); if(value==null||value<=0)return; await app.db.insertExpense(Expense(amount:value,category:category,note:note.text.trim(),createdAt:DateTime.now())); await app.refreshSummary(); setState((){}); }
  @override Widget build(BuildContext context){final app=context.watch<AppController>(); final s=AppStrings(app.bangla); return Scaffold(floatingActionButton:FloatingActionButton.extended(onPressed:_add,icon:const Icon(CupertinoIcons.add),label:Text(s.save)),body:FutureBuilder<List<Expense>>(future:app.db.getExpenses(),builder:(context,p)=>ListView(padding:const EdgeInsets.fromLTRB(16,10,16,110),children:[Text(s.expenses,style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:12),if((p.data??const <Expense>[]).isEmpty)Padding(padding:const EdgeInsets.all(28),child:Center(child:Text(s.noData))),...(p.data??const <Expense>[]).map((e)=>Card(child:ListTile(leading:const Icon(CupertinoIcons.arrow_down_circle),title:Text('৳${e.amount.toStringAsFixed(2)}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${e.category}\n${DateFormat('dd MMM yyyy, hh:mm a').format(e.createdAt)}'))))])));}
}
