import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:intl/intl.dart';
import '../../core/app_controller.dart';
import '../../core/motion/motion_tokens.dart';
import '../../data/models.dart';

class PlayerDetailScreen extends StatefulWidget { final int playerId; const PlayerDetailScreen({super.key,required this.playerId}); @override State<PlayerDetailScreen> createState()=>_PlayerDetailScreenState(); }
class _PlayerDetailScreenState extends State<PlayerDetailScreen> {
  Future<void> _change(String type) async { final app=context.read<AppController>(); final s=AppStrings(app.bangla); final c=TextEditingController(); final result=await showModalBottomSheet<int>(context:context,isScrollControlled:true,builder:(ctx)=>Padding(padding:EdgeInsets.only(left:18,right:18,top:18,bottom:MediaQuery.of(ctx).viewInsets.bottom+18),child:Column(mainAxisSize:MainAxisSize.min,children:[Text(type=='SPEND'?s.spendPoints:type=='REFUND'?s.refundPoints:s.addPoints,style:Theme.of(ctx).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:14),TextField(controller:c,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:s.amount,prefixIcon:const Icon(CupertinoIcons.number),border:OutlineInputBorder(borderRadius:BorderRadius.circular(18))),),const SizedBox(height:14),FilledButton(onPressed:()=>Navigator.pop(ctx,int.tryParse(c.text)),child:Text(s.save))])); if(result==null||result<=0)return; try{await app.db.applyPoints(playerId:widget.playerId,type:type,points:result); await app.refreshSummary(); if(mounted)setState((){});}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Bad state: ',''))));}}
  @override Widget build(BuildContext context){ final app=context.watch<AppController>(); final s=AppStrings(app.bangla); return FutureBuilder<Player?>(future:app.db.getPlayer(widget.playerId),builder:(context,p){final player=p.data; if(player==null)return const Scaffold(body:Center(child:Text('Player not found'))); return Scaffold(appBar:AppBar(title:Text(player.name)),body:ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(borderRadius:BorderRadius.circular(28),gradient:LinearGradient(colors:[Theme.of(context).colorScheme.primaryContainer,Theme.of(context).colorScheme.secondaryContainer])),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${player.points}',style:Theme.of(context).textTheme.displaySmall?.copyWith(fontWeight:FontWeight.w900)),Text(s.bn?'বর্তমান পয়েন্ট':'Current points'),const SizedBox(height:16),if(player.email.isNotEmpty)Text(player.email),if(player.phone.isNotEmpty)Text(player.phone)])),const SizedBox(height:16),Row(children:[Expanded(child:FilledButton.icon(onPressed:()=>_change('ADD'),icon:const Icon(CupertinoIcons.add),label:Text(s.addPoints))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:()=>_change('SPEND'),icon:const Icon(CupertinoIcons.minus),label:Text(s.spendPoints)))]),const SizedBox(height:8),OutlinedButton.icon(onPressed:()=>_change('REFUND'),icon:const Icon(CupertinoIcons.arrow_counterclockwise),label:Text(s.refundPoints)),const SizedBox(height:24),Text(s.history,style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:10),FutureBuilder<List<LedgerEntry>>(future:app.db.getLedger(widget.playerId),builder:(context,l){final list=l.data??const <LedgerEntry>[]; if(list.isEmpty)return Padding(padding:const EdgeInsets.all(24),child:Center(child:Text(s.noData))); return Column(children:list.map((e)=>Padding(padding:const EdgeInsets.only(bottom:9),child:AnimatedContainer(duration:MotionTokens.fast,curve:MotionTokens.curve,child:ListTile(shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18)),tileColor:Theme.of(context).colorScheme.surfaceContainerHighest,leading:Icon(e.type=='SPEND'?CupertinoIcons.minus_circle:e.type=='REFUND'?CupertinoIcons.arrow_counterclockwise_circle:CupertinoIcons.add_circled, color: e.type=='SPEND'?Theme.of(context).colorScheme.error:Theme.of(context).colorScheme.primary),title:Text('${e.type} • ${e.points}'),subtitle:Text(DateFormat('dd MMM yyyy, hh:mm a').format(e.createdAt)),)))) .toList());})]));}}
}
